services:
  backend:
    image: so0omin/backend
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - RDS_HOST=${RDS_HOST}
      - RDS_USERNAME=${RDS_USERNAME}
      - RDS_PASSWORD=${RDS_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JPA_DDL_AUTO=${JPA_DDL_AUTO:-update}
      - JPA_SHOW_SQL=${JPA_SHOW_SQL:-false}
      - APP_BASE_URL=${APP_BASE_URL:-http://localhost:5173}
    restart: unless-stopped

  frontend:
    image: so0omin/frontend
    build: ./frontend
    ports:
      - "5173:80" # 외부 5173 포트를 Nginx 80 포트로 연결
    depends_on:
      - backend
    restart: unless-stopped
