import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useSearchParams, useNavigate } from 'react-router-dom';
import { Header } from '../../components/common/Header'; // 경로가 안 맞으면 ../../ 또는 ../ 로 수정하세요
import { Footer } from '../../components/common/Footer';
import { XCircle, AlertCircle, Home, RotateCcw } from 'lucide-react';
export default function PaymentFailPage() {
    const [searchParams] = useSearchParams();
    const navigate = useNavigate();
    const errorCode = searchParams.get('code');
    const errorMessage = searchParams.get('message');
    const reservationId = searchParams.get('reservationId');
    return (_jsxs("div", { className: "min-h-screen bg-[#fdf4e3]", children: [_jsx(Header, {}), _jsx("main", { className: "max-w-[600px] mx-auto px-6 py-16", children: _jsxs("div", { className: "bg-white rounded-2xl shadow-xl overflow-hidden border border-red-100", children: [_jsxs("div", { className: "bg-red-50 p-8 text-center border-b border-red-100", children: [_jsx("div", { className: "flex justify-center mb-4", children: _jsx("div", { className: "bg-white p-4 rounded-full shadow-sm", children: _jsx(XCircle, { className: "w-12 h-12 text-red-500", strokeWidth: 2 }) }) }), _jsx("h1", { className: "text-2xl font-bold text-gray-900", children: "\uACB0\uC81C\uC5D0 \uC2E4\uD328\uD588\uC2B5\uB2C8\uB2E4" }), _jsx("p", { className: "text-gray-500 mt-2 text-sm", children: "\uC694\uCCAD\uD558\uC2E0 \uACB0\uC81C\uAC00 \uC815\uC0C1\uC801\uC73C\uB85C \uCC98\uB9AC\uB418\uC9C0 \uC54A\uC558\uC2B5\uB2C8\uB2E4." })] }), _jsxs("div", { className: "p-8", children: [errorMessage && (_jsxs("div", { className: "bg-red-50 rounded-xl p-5 mb-8 border border-red-200 flex items-start gap-3", children: [_jsx(AlertCircle, { className: "w-5 h-5 text-red-600 shrink-0 mt-0.5" }), _jsxs("div", { children: [_jsx("h3", { className: "text-red-800 font-bold text-sm mb-1", children: "\uC624\uB958 \uB0B4\uC6A9" }), _jsx("p", { className: "text-red-700 text-sm", children: errorMessage }), errorCode && (_jsxs("p", { className: "text-red-500 text-xs mt-1", children: ["Error Code: ", errorCode] }))] })] })), _jsxs("div", { className: "text-center text-gray-600 text-sm mb-8 leading-relaxed", children: ["\uC77C\uC2DC\uC801\uC778 \uC624\uB958\uC77C \uC218 \uC788\uC2B5\uB2C8\uB2E4.", _jsx("br", {}), "\uC7A0\uC2DC \uD6C4 \uB2E4\uC2DC \uC2DC\uB3C4\uD574 \uC8FC\uC2DC\uAC70\uB098,", _jsx("br", {}), "\uBB38\uC81C\uAC00 \uC9C0\uC18D\uB418\uBA74 \uACE0\uAC1D\uC13C\uD130\uB85C \uBB38\uC758\uD574 \uC8FC\uC138\uC694."] }), _jsxs("div", { className: "flex gap-3", children: [_jsxs("button", { onClick: () => navigate('/'), className: "flex-1 flex items-center justify-center gap-2 px-6 py-4 bg-white border border-gray-300 text-gray-700 rounded-xl hover:bg-gray-50 transition-all font-medium", children: [_jsx(Home, { className: "w-4 h-4" }), "\uD648\uC73C\uB85C"] }), _jsxs("button", { onClick: () => navigate(reservationId ? `/payment?reservationId=${reservationId}` : '/payment'), className: "flex-1 flex items-center justify-center gap-2 px-6 py-4 bg-[#eb4d32] text-white rounded-xl hover:bg-[#d43d22] transition-all font-medium shadow-md shadow-orange-100", children: [_jsx(RotateCcw, { className: "w-4 h-4" }), "\uB2E4\uC2DC \uC2DC\uB3C4\uD558\uAE30"] })] })] })] }) }), _jsx(Footer, {})] }));
}
