import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const paymentMethodLabel = {
    CARD: '카드결제',
    TRANSFER: '실시간 계좌이체',
    VIRTUAL_ACCOUNT: '가상계좌',
    MOBILE_PHONE: '휴대폰 결제',
};
export function PaymentSummary({ paymentData, selectedPaymentMethod, onPayment, isProcessing = false, }) {
    const methodText = paymentMethodLabel[selectedPaymentMethod] ?? '결제수단 선택';
    return (_jsx("div", { className: "w-[340px]", children: _jsxs("div", { className: "bg-white border-2 border-gray-300 rounded-lg p-6 sticky top-4", children: [_jsx("h2", { className: "text-xl mb-6", children: "\uACB0\uC81C\uAE08\uC561" }), _jsx("div", { className: "bg-[#f5e6d3] rounded-lg p-4 mb-3", children: _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "flex justify-between", children: [_jsx("span", { children: "\uC778\uC6D0" }), _jsx("span", { children: paymentData.adultCount })] }), _jsx("div", { className: "h-px bg-gray-300" }), _jsxs("div", { className: "flex justify-between", children: [_jsx("span", { children: "\uAE08\uC561" }), _jsxs("span", { children: [paymentData.totalAmount.toLocaleString(), "\uC6D0"] })] })] }) }), _jsx("div", { className: "flex justify-center -my-3 relative z-10", children: _jsx("div", { className: "w-8 h-8 rounded-full bg-[#eb4d32] flex items-center justify-center", children: _jsx("span", { className: "text-white font-bold", children: "-" }) }) }), _jsx("div", { className: "bg-[#f5e6d3] rounded-lg p-4 mb-6", children: _jsxs("div", { className: "flex justify-between items-center", children: [_jsx("span", { children: "\uD560\uC778\uAE08\uC561" }), _jsxs("span", { children: [paymentData.discountAmount.toLocaleString(), "\uC6D0"] })] }) }), _jsxs("div", { className: "bg-[#f5e6d3] rounded-lg p-4 mb-6", children: [_jsxs("div", { className: "flex justify-between items-center mb-4", children: [_jsx("span", { children: "\uCD5C\uC885 \uACB0\uC81C" }), _jsxs("span", { className: "text-2xl text-[#eb4d32]", children: [paymentData.finalAmount.toLocaleString(), "\uC6D0"] })] }), _jsxs("div", { className: "text-sm text-gray-700", children: [_jsx("p", { children: "\uACB0\uC81C\uC218\uB2E8" }), _jsx("p", { className: "mt-2", children: methodText })] })] }), _jsxs("div", { className: "flex gap-3", children: [_jsx("button", { className: "flex-1 py-3 bg-white border-2 border-gray-300 rounded hover:bg-gray-50 transition-colors", children: "\uC774\uC804" }), _jsx("button", { onClick: onPayment, disabled: isProcessing, className: "flex-1 py-3 bg-[#eb4d32] text-white rounded hover:bg-[#d43d22] transition-colors disabled:opacity-50 disabled:cursor-not-allowed", children: isProcessing ? '처리중...' : '결제' })] })] }) }));
}
